name: CI AND IT

on: [pull_request, push]

jobs:
  CI:
    runs-on: ubuntu-18.04
    timeout-minutes: 180
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          DM: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$DM"
          echo "${github.event}"
      - name: 'set env'
        run: export MAVEN_OPTS='-Dmaven.repo.local=.m2/repository -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:-UseGCOverheadLimit -Xmx3g'
      - name: 'Install & Test'
        run: |
          ./mvnw -P"agent,backend,ui,dist,CI-with-IT" -DrepoToken=iiH0Deepi2t2dHJ3wWMBUg6XcOHBnsyUI -DpullRequest=${ghprbPullLink} clean cobertura:cobertura verify coveralls:report install
          ./mvnw javadoc:javadoc -Dmaven.test.skip=true
      - name: 'Check Dependencies Licenses'
        run: tools/dependencies/check-LICENSE.sh
