# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Agent Plugins Tests

on: [pull_request, push]

jobs:
  group1:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build SkyWalking Agent
        run: ./mvnw clean package -DskipTests -Pagent
      - name: Build the Docker image
        run: bash tools/ci/agent-build-condition.sh &&  ./mvnw -f test/plugin/pom.xml clean package -DskipTests docker:build -DBUILD_NO=local
      - name: Run spring-tx 4.x+ (10)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh spring-tx-scenario
      - name: Run spring 4.3.x-5.2.x (54)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh spring-4.3.x-scenario
      - name: Run dubbo 2.5.x-2.6.x (10)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh dubbo-2.5.x-scenario
      - name: Run dubbo 2.7.x (4)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh dubbo-2.7.x-scenario
      - name: Run okhttp 3.0.x-3.14.x (34)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh okhttp-scenario
  group2:
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build SkyWalking Agent
        run: bash tools/ci/agent-build-condition.sh &&  ./mvnw clean package -DskipTests -Pagent
      - name: Build the Docker image
        run: bash tools/ci/agent-build-condition.sh &&  ./mvnw -f test/plugin/pom.xml clean package -DskipTests docker:build -DBUILD_NO=local
      - name: Run redisson 3.x (37)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh redisson-scenario
      - name: Run spring 3.1.x-4.0.x (25)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh spring-3.1.x-scenario
      - name: Run spring-cloud-gateway 2.1.x (3)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh gateway-scenario
      - name: Run elasticsearch 5.x (3)
        run: bash tools/ci/agent-build-condition.sh &&  bash test/plugin/run.sh elasticsearch-5.x-scenario
